### PR TITLE
Changes to the side menu and wording of buttons, ...

### PR DESCRIPTION
**Pull request by salamander2**
See the notes in the commits. 
Some of it is a kludge, namely checking if the user == 'teacher', but if I try to add another field to the users table via a migration it will probably delete everything in the database again.

### CODE REVIEW

**Comment by Volxz** [comment]
Why not just check if they are authenticated instead of if they are on the teacher account?

**Comment by salamander2** [comment]
This is a small item and not really that important, but ideally, we need 3 types of users:

1. admin (we have this)
2. normal users who can start kiosks and manage them (we have this)
3. view only users (only the teacher account) who should not even see the menu entry that says "User Tasks" and "Start Kiosks". They can only view logs (and maybe export them). I would prefer to have a "viewOnly" field in the users table.
4. not-logged on state (we have this)

**Comment by Volxz** [comment]
Couldn't view only users just be users without kiosks assigned to them?

**Comment by salamander2** [comment]
Yes, that would do exactly what we want.  So we just need to check if they have kiosks assigned to them or not. Thanks.

**Comment by Volxz** [comment]
I'll fork this PR and do a quick fix

**Pull request merged**
